MovieBest.MVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieBest.BLL.Services.Interfaces;
using MovieBest.DAL.Entities;

namespace MovieBest.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;

        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            var genres = await _genreService.GetAllGenresAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
				genres = genres.Where(m => m.Name.ToUpper().Contains(searchString.ToUpper())).ToList();
			}
            return View(genres);
        }    

        [HttpGet]
        public IActionResult AddNew()
            => View();
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNew(Genre genre)
        {
            if (ModelState.IsValid)
            {
                await _genreService.AddNewGenreAsync(genre);
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var genre = await _genreService.GetGenreByIdAsync(Id);
            if (genre == null)
                return NotFound();

            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {
                await _genreService.updateGenreAsync(genre);
                return RedirectToAction("Index");
            }

            return View(genre);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var genre = await _genreService.GetGenreByIdAsync(Id);
            if (genre == null)
                return NotFound();

            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int Id)
        {
            if (!await _genreService.DeleteGenreAsync(Id))
                return NotFound();

            return RedirectToAction("Index");
        }
    }
}

MovieBest.MVC/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieBest.DAL.Entities;
using MovieBest.DAL.Models;

namespace MovieBest.MVC.Controllers
{
	[Authorize]
	public class ProfileController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
		private readonly SignInManager<ApplicationUser> _signInManager;
		private readonly ILogger<ProfileController> _logger;

		public ProfileController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager
			,SignInManager<ApplicationUser> signInManager, ILogger<ProfileController> logger)
        {
			_userManager = userManager;
            _roleManager = roleManager;
			_signInManager = signInManager;
			_logger = logger;
		}

		[HttpGet]
        public async Task<IActionResult> Index()
		{
			var user = await _userManager.GetUserAsync(User);
			
			if (user == null)
				return RedirectToAction("Login", "Account");

			var userRoles = await _userManager.GetRolesAsync(user);

			var model = new ProfileViewModel()
			{
				userName = user.UserName,
				Email = user.Email,
				userRoles = userRoles
			};

			return View(model);
		}

		[HttpGet]
		public IActionResult ChangePassword()
			=> View();

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
		{
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
				return RedirectToAction("Login", "Account");

			try
			{
				if (ModelState.IsValid)
				{
					var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
					if (result.Succeeded)
					{
						await _signInManager.SignOutAsync();
						TempData["SuccessMessage"] = "Your Password Hase Been Changed Successfully";
						return RedirectToAction("Login", "Account");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error.Description);
					}
				}
			}
			catch (Exception ex)
			{
				_logger.LogError(ex.Message);
				return View(model);
			}
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> DeleteProfile()
		{ 
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
				return RedirectToAction("Login", "Account");

			return View(user);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteProfileConfirm()
		{
			var user = await _userManager.GetUserAsync(User);
			if (user == null)
				return RedirectToAction("Login", "Account");

			try
			{
				var result = await _userManager.DeleteAsync(user);
				if (result.Succeeded)
				{
					TempData["DeleteProfile"] = "Profile Deleted Successfully";
					await _signInManager.SignOutAsync();
					return RedirectToAction("Index", "Home");
				}
			}
			catch (Exception ex)
			{
				_logger.LogError(ex.Message);
				return View();
			}
			return View();
		}
	}
}

MovieBest.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movies.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movies.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movies.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Movies.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieBest.MVC/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Planet</title>
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/font-awesome.min.css" rel="stylesheet">
		<link href="/css/global.css" rel="stylesheet">
		<link href="/css/index.css" rel="stylesheet">

		<link href="https://fonts.googleapis.com/css2?family=Rajdhani&display=swap" rel="stylesheet">
		<script src="/js/bootstrap.bundle.min.js"></script>

		<meta name="viewport" content="width=device-width" />
		<title>@ViewBag.Title</title>

	

</head>
<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.1.8/af-2.7.0/b-3.1.2/fc-5.0.3/sc-2.4.3/sb-1.8.1/sp-2.3.3/sl-2.1.0/datatables.min.js"></script>
	<section id="top">
		<div class="container">
			<div class="row top_1">
				<div class="col-md-3">
					<div class="top_1l pt-1">
						<h3 class="mb-0"><a class="text-white" href="index.html"><i class="fa fa-video-camera col_red me-1"></i> Planet</a></h3>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="header">
		<nav class="navbar navbar-expand-md navbar-light" id="navbar_sticky">
			<div class="container">
				<a class="navbar-brand text-white fw-bold" href="index.html"><i class="fa fa-video-camera col_red me-1"></i> Planet</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mb-0">

						@if (User.Identity.IsAuthenticated == false)
						{

							<li class="nav-item">
								<a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
							</li>
						}
						else
						{

						<li class="nav-item">
							<a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-action="AboutUs" asp-controller="Home" >About Us</a>
						</li>

						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Admin
								</a>
								<ul class="dropdown-menu drop_1" aria-labelledby="navbarDropdown">
									<li><a class="dropdown-item" asp-action="Index" asp-controller="Movie">Movies</a></li>
									<li><a class="dropdown-item" asp-action="Index" asp-controller="Genre">Genres</a></li>
									<li><a class="dropdown-item" asp-action="Users" asp-controller="Admin">Users</a></li>
									<li><a class="dropdown-item border-0" asp-action="GetRoles" asp-controller="Admin" >Roles</a></li>
								</ul>
							</li>
						}
						<li class="nav-item">
							<a class="nav-link" asp-action="Index" asp-controller="Profile" >Profile</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-action="LogOut" asp-controller="Account">LogOut</a>
						</li>
						}

					</ul>
				</div>
			</div>
		</nav>
    </section>
    <div>
        @RenderBody()
		@RenderSection("scripts", required: false)
    </div>
</body>
</html>